JoinTitle: "§e§kiii§r §l§cM§6M§eO§aR§bP§dG §r§e§kiii§r"
JoinSubtitle: "§bWelcome§f {player}§b !§r"
WorldTitle: "§e§kiii§r §l§6W§eA§6R§eP §r§e§kiii§r"
WorldSubtitle: "§bWelcome §f{player} §bto§f {world}§b !§r"
Fadein: 4
Duration: 4
Fadeout: 4